export type ExerciseType = 'facial' | 'body';
export type SideControl = 'left' | 'right' | 'both';
export type DifficultyLevel = 'beginner' | 'intermediate' | 'advanced';

export interface Exercise {
  id: string;
  type: ExerciseType;
  category: string;
  name: string;
  nameKey: string;
  description: string;
  descriptionKey: string;
  benefits: string[];
  benefitsKeys: string[];
  duration: number;
  repetitions?: number;
  sideControl: SideControl;
  warnings: string[];
  warningsKeys: string[];
  technique: string[];
  techniqueKeys: string[];
  difficulty: DifficultyLevel;
  icon: string;
}

export const facialExercises: Exercise[] = [
  {
    id: 'jawline-clench',
    type: 'facial',
    category: 'jawline',
    name: 'Jawline Clench',
    nameKey: 'jawlineClench',
    description: 'Tense your jaw muscles by clenching your teeth and holding the position. Focus on the masseter muscles on both sides.',
    descriptionKey: 'jawlineClenchDesc',
    benefits: [
      'Strengthens jawline',
      'Defines facial contours',
      'Improves masseter muscle tone',
      'Enhances lower face structure',
    ],
    benefitsKeys: [
      'jawlineClenchBenefits',
    ],
    duration: 30,
    repetitions: 10,
    sideControl: 'both',
    warnings: [
      'Do not clench too tightly',
      'Avoid grinding teeth',
      'Stop if you feel jaw pain',
    ],
    warningsKeys: [
      'jawlineClenchWarnings',
    ],
    technique: [
      'Sit or stand with proper posture',
      'Close mouth gently',
      'Clench teeth with moderate pressure',
      'Focus on engaging both masseters equally',
      'Hold for 3-5 seconds',
      'Release and relax',
      'Repeat for recommended repetitions',
    ],
    techniqueKeys: [],
    difficulty: 'beginner',
    icon: 'Jaw',
  },
  {
    id: 'jawline-resistance',
    type: 'facial',
    category: 'jawline',
    name: 'Jawline Resistance',
    nameKey: 'jawlineResistance',
    description: 'Use your hand to apply gentle resistance against your jaw as you open and close your mouth.',
    descriptionKey: 'jawlineResistanceDesc',
    benefits: [
      'Builds jaw strength',
      'Improves muscle definition',
      'Enhances lower face structure',
      'Increases muscle control',
    ],
    benefitsKeys: [
      'jawlineResistanceBenefits',
    ],
    duration: 20,
    repetitions: 8,
    sideControl: 'both',
    warnings: [
      'Use gentle pressure only',
      'Avoid overextension of jaw joint',
      'Stop if you feel discomfort',
    ],
    warningsKeys: [
      'jawlineResistanceWarnings',
    ],
    technique: [
      'Place hand under chin',
      'Apply gentle upward resistance',
      'Open mouth slowly against resistance',
      'Close mouth maintaining pressure',
      'Keep movements controlled',
      'Focus on symmetrical engagement',
      'Repeat for both sides',
    ],
    techniqueKeys: [],
    difficulty: 'intermediate',
    icon: 'Anchor',
  },
  {
    id: 'tongue-posture',
    type: 'facial',
    category: 'jawline',
    name: 'Tongue Posture (Mewing)',
    nameKey: 'tonguePosture',
    description: 'Press the entire surface of your tongue against the roof of your mouth, keeping teeth slightly apart.',
    descriptionKey: 'tonguePostureDesc',
    benefits: [
      'Defines jawline over time',
      'Improves facial structure',
      'Promotes proper tongue positioning',
      'Enhances nasal breathing',
    ],
    benefitsKeys: [
      'tonguePostureBenefits',
    ],
    duration: 60,
    sideControl: 'both',
    warnings: [
      'Do not force the tongue',
      'Ensure comfortable placement',
      'Practice gradually',
      'Breathe through nose',
    ],
    warningsKeys: [
      'tonguePostureWarnings',
    ],
    technique: [
      'Relax jaw completely',
      'Place tongue tip behind upper front teeth',
      'Press entire tongue surface to roof',
      'Keep teeth lightly apart',
      'Maintain position throughout exercise',
      'Focus on even pressure distribution',
      'Practice daily for best results',
    ],
    techniqueKeys: [],
    difficulty: 'beginner',
    icon: 'Smile',
  },
  {
    id: 'cheek-lifts',
    type: 'facial',
    category: 'cheeks',
    name: 'Cheek Lifts',
    nameKey: 'cheekLifts',
    description: 'Smile broadly while keeping your lips closed, then push your cheeks upward toward your eyes.',
    descriptionKey: 'cheekLiftsDesc',
    benefits: [
      'Tones cheek muscles',
      'Reduces sagging',
      'Enhances facial definition',
      'Improves mid-face fullness',
    ],
    benefitsKeys: [
      'cheekLiftsBenefits',
    ],
    duration: 15,
    repetitions: 15,
    sideControl: 'both',
    warnings: [
      'Avoid excessive smiling that causes wrinkles',
      'Maintain controlled movement',
      'Don\'t overexert facial muscles',
    ],
    warningsKeys: [
      'cheekLiftsWarnings',
    ],
    technique: [
      'Start with relaxed face',
      'Close lips gently',
      'Smile broadly with closed mouth',
      'Push cheeks upward toward eyes',
      'Hold at peak for 2-3 seconds',
      'Relax and return to neutral',
      'Maintain symmetrical movement',
    ],
    techniqueKeys: [],
    difficulty: 'beginner',
    icon: 'Wand2',
  },
  {
    id: 'cheek-puffing',
    type: 'facial',
    category: 'cheeks',
    name: 'Cheek Puffing',
    nameKey: 'cheekPuffing',
    description: 'Inflate your cheeks with air, then transfer the air from side to side while holding.',
    descriptionKey: 'cheekPuffingDesc',
    benefits: [
      'Strengthens buccinator muscles',
      'Improves cheek fullness',
      'Tones facial structure',
      'Enhances muscle control',
    ],
    benefitsKeys: [
      'cheekPuffingBenefits',
    ],
    duration: 5,
    repetitions: 20,
    sideControl: 'both',
    warnings: [
      'Breathe normally between holds',
      'Do not overexert facial muscles',
      'Keep lips sealed',
    ],
    warningsKeys: [
      'cheekPuffingWarnings',
    ],
    technique: [
      'Take air into mouth',
      'Close lips tightly',
      'Puff cheeks with air',
      'Transfer air to left side',
      'Hold for 2-3 seconds',
      'Transfer to right side',
      'Hold for 2-3 seconds',
      'Repeat side to side',
    ],
    techniqueKeys: [],
    difficulty: 'beginner',
    icon: 'Cloud',
  },
  {
    id: 'cheek-resistance',
    type: 'facial',
    category: 'cheeks',
    name: 'Cheek Resistance',
    nameKey: 'cheekResistance',
    description: 'Use your fingers to apply gentle pressure on your cheeks while smiling against the resistance.',
    descriptionKey: 'cheekResistanceDesc',
    benefits: [
      'Builds cheek muscle strength',
      'Enhances facial contour',
      'Improves muscle control',
      'Tones mid-face area',
    ],
    benefitsKeys: [
      'cheekResistanceBenefits',
    ],
    duration: 10,
    repetitions: 12,
    sideControl: 'both',
    warnings: [
      'Apply light pressure only',
      'Avoid pinching or pulling skin',
      'Keep movements gentle',
    ],
    warningsKeys: [
      'cheekResistanceWarnings',
    ],
    technique: [
      'Place fingers on cheek area',
      'Apply gentle outward pressure',
      'Smile against the resistance',
      'Hold contraction for 3-4 seconds',
      'Relax and release pressure',
      'Repeat on both cheeks equally',
      'Maintain symmetrical pressure',
    ],
    techniqueKeys: [],
    difficulty: 'intermediate',
    icon: 'Hand',
  },
  {
    id: 'eye-focus',
    type: 'facial',
    category: 'eyes',
    name: 'Eye Focus Training',
    nameKey: 'eyeFocus',
    description: 'Look at a distant object, then focus on something close, repeatedly switching between distances.',
    descriptionKey: 'eyeFocusDesc',
    benefits: [
      'Strengthens eye muscles',
      'Improves focus coordination',
      'Enhances facial balance',
      'Reduces eye strain',
    ],
    benefitsKeys: [
      'eyeFocusBenefits',
    ],
    duration: 3,
    repetitions: 30,
    sideControl: 'both',
    warnings: [
      'Blink regularly',
      'Avoid straining',
      'Take breaks if eyes become tired',
    ],
    warningsKeys: [
      'eyeFocusWarnings',
    ],
    technique: [
      'Find a distant object (20+ feet)',
      'Focus on it clearly',
      'Switch to a nearby object (6-12 inches)',
      'Focus intensely',
      'Repeat switching between distances',
      'Keep head still, move only eyes',
      'Blink between each focus change',
    ],
    techniqueKeys: [],
    difficulty: 'beginner',
    icon: 'Eye',
  },
  {
    id: 'eye-circles',
    type: 'facial',
    category: 'eyes',
    name: 'Eye Circular Movements',
    nameKey: 'eyeCircles',
    description: 'Slowly move your eyes in circular patterns, first clockwise then counter-clockwise.',
    descriptionKey: 'eyeCirclesDesc',
    benefits: [
      'Improves eye muscle flexibility',
      'Reduces eye strain',
      'Enhances peripheral awareness',
      'Coordinates eye movements',
    ],
    benefitsKeys: [
      'eyeCirclesBenefits',
    ],
    duration: 2,
    repetitions: 20,
    sideControl: 'both',
    warnings: [
      'Move slowly and smoothly',
      'Avoid rapid or jerky movements',
      'Stop if you feel dizzy',
    ],
    warningsKeys: [
      'eyeCirclesWarnings',
    ],
    technique: [
      'Keep head completely still',
      'Look straight ahead',
      'Move eyes in clockwise circle',
      'Complete full circle slowly',
      'Repeat for specified reps',
      'Switch to counter-clockwise',
      'Maintain smooth movements',
    ],
    techniqueKeys: [],
    difficulty: 'beginner',
    icon: 'RefreshCw',
  },
  {
    id: 'eyebrow-lifts',
    type: 'facial',
    category: 'eyes',
    name: 'Eyebrow Lifts',
    nameKey: 'eyebrowLifts',
    description: 'Raise your eyebrows as high as possible, hold briefly, then relax and repeat.',
    descriptionKey: 'eyebrowLiftsDesc',
    benefits: [
      'Tones forehead muscles',
      'Reduces brow sagging',
      'Enhances upper facial expression',
      'Improves eye area appearance',
    ],
    benefitsKeys: [
      'eyebrowLiftsBenefits',
    ],
    duration: 4,
    repetitions: 15,
    sideControl: 'both',
    warnings: [
      'Avoid creating deep forehead wrinkles',
      'Maintain smooth movements',
      'Don\'t force too hard',
    ],
    warningsKeys: [
      'eyebrowLiftsWarnings',
    ],
    technique: [
      'Start with relaxed forehead',
      'Raise both eyebrows as high as possible',
      'Hold at peak for 2-3 seconds',
      'Relax completely',
      'Ensure symmetrical movement',
      'Repeat for recommended reps',
      'Focus on frontalis muscle engagement',
    ],
    techniqueKeys: [],
    difficulty: 'beginner',
    icon: 'ArrowUp',
  },
  {
    id: 'neck-tilts',
    type: 'facial',
    category: 'neck',
    name: 'Neck Tilts',
    nameKey: 'neckTilts',
    description: 'Gently tilt your head forward, backward, and to each side, stretching the neck muscles.',
    descriptionKey: 'neckTiltsDesc',
    benefits: [
      'Improves neck flexibility',
      'Reduces tension',
      'Enhances jawline appearance',
      'Relieves muscle tightness',
    ],
    benefitsKeys: [
      'neckTiltsBenefits',
    ],
    duration: 10,
    repetitions: 8,
    sideControl: 'both',
    warnings: [
      'Move slowly and smoothly',
      'Avoid extreme ranges',
      'Stop if you feel pain',
    ],
    warningsKeys: [
      'neckTiltsWarnings',
    ],
    technique: [
      'Sit or stand with good posture',
      'Tilt head forward slowly',
      'Bring chin toward chest',
      'Hold gentle stretch',
      'Return to neutral',
      'Tilt head backward',
      'Tilt to each side alternately',
    ],
    techniqueKeys: [],
    difficulty: 'beginner',
    icon: 'MoveDown',
  },
  {
    id: 'neck-rotations',
    type: 'facial',
    category: 'neck',
    name: 'Neck Rotations',
    nameKey: 'neckRotations',
    description: 'Slowly rotate your head in circles, first clockwise then counter-clockwise.',
    descriptionKey: 'neckRotationsDesc',
    benefits: [
      'Increases neck mobility',
      'Releases muscle tension',
      'Improves posture',
      'Enhances neck flexibility',
    ],
    benefitsKeys: [
      'neckRotationsBenefits',
    ],
    duration: 4,
    repetitions: 10,
    sideControl: 'both',
    warnings: [
      'Keep movements gentle',
      'Avoid cracking or popping sounds',
      'Stop if you feel discomfort',
    ],
    warningsKeys: [
      'neckRotationsWarnings',
    ],
    technique: [
      'Relax neck and shoulders',
      'Start with neutral head position',
      'Rotate head clockwise slowly',
      'Complete full circle',
      'Keep shoulders down',
      'Switch to counter-clockwise',
      'Perform equal reps each direction',
    ],
    techniqueKeys: [],
    difficulty: 'beginner',
    icon: 'RefreshCw',
  },
  {
    id: 'chin-tucks',
    type: 'facial',
    category: 'neck',
    name: 'Chin Tucks',
    nameKey: 'chinTucks',
    description: 'Pull your chin straight back as if making a double chin, hold, then release.',
    descriptionKey: 'chinTucksDesc',
    benefits: [
      'Strengthens neck flexors',
      'Improves forward head posture',
      'Defines jawline',
      'Reduces neck strain',
    ],
    benefitsKeys: [
      'chinTucksBenefits',
    ],
    duration: 5,
    repetitions: 12,
    sideControl: 'both',
    warnings: [
      'Ensure smooth movement',
      'Avoid jerking',
      'Align with spine properly',
    ],
    warningsKeys: [
      'chinTucksWarnings',
    ],
    technique: [
      'Sit or stand tall',
      'Keep eyes level',
      'Pull chin straight back',
      'Create slight double chin',
      'Hold for 3-4 seconds',
      'Release slowly',
      'Focus on deep neck flexors',
    ],
    techniqueKeys: [],
    difficulty: 'beginner',
    icon: 'ArrowLeft',
  },
  {
    id: 'head-alignment',
    type: 'facial',
    category: 'headPosture',
    name: 'Head Alignment Training',
    nameKey: 'headAlignment',
    description: 'Practice aligning your head directly above your shoulders, maintaining neutral position.',
    descriptionKey: 'headAlignmentDesc',
    benefits: [
      'Corrects forward head posture',
      'Improves facial symmetry',
      'Reduces neck strain',
      'Enhances overall appearance',
    ],
    benefitsKeys: [
      'headAlignmentBenefits',
    ],
    duration: 30,
    sideControl: 'both',
    warnings: [
      'Use a mirror for feedback',
      'Maintain awareness throughout day',
      'Don\'t overcorrect suddenly',
    ],
    warningsKeys: [
      'headAlignmentWarnings',
    ],
    technique: [
      'Stand against a wall',
      'Align ears with shoulders',
      'Keep chin parallel to floor',
      'Maintain neutral spine',
      'Hold position',
      'Check alignment in mirror',
      'Practice regularly throughout day',
    ],
    techniqueKeys: [],
    difficulty: 'beginner',
    icon: 'AlignCenterVertical',
  },
  {
    id: 'head-level',
    type: 'facial',
    category: 'headPosture',
    name: 'Head Leveling',
    nameKey: 'headLevel',
    description: 'Use a water level or app to ensure your head is perfectly level when standing still.',
    descriptionKey: 'headLevelDesc',
    benefits: [
      'Identifies asymmetries',
      'Improves balance awareness',
      'Trains proper alignment',
      'Develops postural consciousness',
    ],
    benefitsKeys: [
      'headLevelBenefits',
    ],
    duration: 20,
    sideControl: 'both',
    warnings: [
      'Do not obsess over minor asymmetries',
      'Focus on gradual improvement',
      'Use as training tool only',
    ],
    warningsKeys: [
      'headLevelWarnings',
    ],
    technique: [
      'Stand on level surface',
      'Place level on top of head',
      'Adjust head position',
      'Achieve perfect level',
      'Maintain position briefly',
      'Memorize the feeling',
      'Practice without level regularly',
    ],
    techniqueKeys: [],
    difficulty: 'intermediate',
    icon: 'Ruler',
  },
  {
    id: 'mirror-training',
    type: 'facial',
    category: 'headPosture',
    name: 'Mirror Awareness Training',
    nameKey: 'mirrorTraining',
    description: 'Practice maintaining symmetrical facial expressions and head position in front of a mirror.',
    descriptionKey: 'mirrorTrainingDesc',
    benefits: [
      'Develops symmetry awareness',
      'Improves muscle balance',
      'Enhances facial control',
      'Increases conscious awareness',
    ],
    benefitsKeys: [
      'mirrorTrainingBenefits',
    ],
    duration: 45,
    sideControl: 'both',
    warnings: [
      'Use for short periods',
      'Avoid self-criticism',
      'Focus on improvement not perfection',
    ],
    warningsKeys: [
      'mirrorTrainingWarnings',
    ],
    technique: [
      'Stand in front of mirror',
      'Observe natural asymmetries',
      'Practice symmetrical expressions',
      'Maintain neutral head position',
      'Check from multiple angles',
      'Hold symmetrical positions',
      'Develop muscle memory',
    ],
    techniqueKeys: [],
    difficulty: 'beginner',
    icon: 'Monitor',
  },
];

export const bodyExercises: Exercise[] = [
  {
    id: 'shoulder-rolls',
    type: 'body',
    category: 'shoulders',
    name: 'Shoulder Rolls',
    nameKey: 'shoulderRolls',
    description: 'Roll your shoulders forward in circles, then backward, focusing on smooth movements.',
    descriptionKey: 'shoulderRollsDesc',
    benefits: [
      'Improves shoulder mobility',
      'Reduces tension',
      'Enhances upper body symmetry',
      'Relieves shoulder stress',
    ],
    benefitsKeys: [
      'shoulderRollsBenefits',
    ],
    duration: 3,
    repetitions: 20,
    sideControl: 'both',
    warnings: [
      'Move slowly',
      'Avoid shrugging',
      'Maintain relaxed posture',
    ],
    warningsKeys: [
      'shoulderRollsWarnings',
    ],
    technique: [
      'Stand or sit comfortably',
      'Relax shoulders completely',
      'Roll shoulders forward slowly',
      'Complete full circles',
      'Switch to backward direction',
      'Keep movements smooth',
      'Breathe naturally throughout',
    ],
    techniqueKeys: [],
    difficulty: 'beginner',
    icon: 'RefreshCw',
  },
  {
    id: 'shoulder-squeezes',
    type: 'body',
    category: 'shoulders',
    name: 'Shoulder Squeezes',
    nameKey: 'shoulderSqueezes',
    description: 'Squeeze your shoulder blades together, hold briefly, then release and repeat.',
    descriptionKey: 'shoulderSqueezesDesc',
    benefits: [
      'Strengthens back muscles',
      'Improves posture',
      'Enhances shoulder definition',
      'Opens chest area',
    ],
    benefitsKeys: [
      'shoulderSqueezesBenefits',
    ],
    duration: 4,
    repetitions: 15,
    sideControl: 'both',
    warnings: [
      'Do not over-squeeze',
      'Maintain relaxed shoulders between repetitions',
      'Keep neck relaxed',
    ],
    warningsKeys: [
      'shoulderSqueezesWarnings',
    ],
    technique: [
      'Stand or sit tall',
      'Squeeze shoulder blades together',
      'Hold contraction for 2-3 seconds',
      'Release and relax',
      'Keep shoulders away from ears',
      'Focus on mid-back engagement',
      'Repeat with control',
    ],
    techniqueKeys: [],
    difficulty: 'beginner',
    icon: 'ArrowIn',
  },
  {
    id: 'unilateral-shoulder',
    type: 'body',
    category: 'shoulders',
    name: 'Unilateral Shoulder Raises',
    nameKey: 'unilateralShoulder',
    description: 'Raise one shoulder at a time, focusing on balanced movement on both sides.',
    descriptionKey: 'unilateralShoulderDesc',
    benefits: [
      'Corrects shoulder asymmetry',
      'Improves individual side awareness',
      'Builds balanced strength',
      'Identifies weak areas',
    ],
    benefitsKeys: [
      'unilateralShoulderBenefits',
    ],
    duration: 3,
    repetitions: 12,
    sideControl: 'both',
    warnings: [
      'Perform equal repetitions on each side',
      'Avoid compensating with stronger side',
      'Start with weaker side first',
    ],
    warningsKeys: [
      'unilateralShoulderWarnings',
    ],
    technique: [
      'Stand with relaxed posture',
      'Lift one shoulder toward ear',
      'Keep other shoulder relaxed',
      'Hold at top briefly',
      'Lower with control',
      'Repeat on same side',
      'Switch to other shoulder',
    ],
    techniqueKeys: [],
    difficulty: 'beginner',
    icon: 'ArrowUp',
  },
  {
    id: 'wall-angles',
    type: 'body',
    category: 'back',
    name: 'Wall Angels',
    nameKey: 'wallAngles',
    description: 'Stand against a wall with arms at 90 degrees, slide arms up and down while maintaining contact.',
    descriptionKey: 'wallAnglesDesc',
    benefits: [
      'Improves posture alignment',
      'Strengthens back muscles',
      'Opens chest area',
      'Enhances shoulder mobility',
    ],
    benefitsKeys: [
      'wallAnglesBenefits',
    ],
    duration: 30,
    repetitions: 10,
    sideControl: 'both',
    warnings: [
      'Keep back flat against wall',
      'Move arms slowly',
      'Avoid straining shoulders',
    ],
    warningsKeys: [
      'wallAnglesWarnings',
    ],
    technique: [
      'Stand with back to wall',
      'Place feet 6 inches from wall',
      'Bend elbows at 90 degrees',
      'Press arms and hands to wall',
      'Slide arms upward',
      'Slide arms downward',
      'Maintain wall contact throughout',
    ],
    techniqueKeys: [],
    difficulty: 'intermediate',
    icon: 'LayoutTemplate',
  },
  {
    id: 'cat-cow',
    type: 'body',
    category: 'back',
    name: 'Cat-Cow Stretch',
    nameKey: 'catCow',
    description: 'Alternate between arching and rounding your back on hands and knees position.',
    descriptionKey: 'catCowDesc',
    benefits: [
      'Increases spinal flexibility',
      'Releases back tension',
      'Improves posture awareness',
      'Enhances spinal mobility',
    ],
    benefitsKeys: [
      'catCowBenefits',
    ],
    duration: 4,
    repetitions: 12,
    sideControl: 'both',
    warnings: [
      'Move smoothly',
      'Avoid extreme ranges',
      'Listen to your body',
    ],
    warningsKeys: [
      'catCowWarnings',
    ],
    technique: [
      'Start on hands and knees',
      'Arch back down (cow position)',
      'Lift head and tailbone',
      'Round back up (cat position)',
      'Tuck chin and tailbone',
      'Alternate between positions',
      'Move with your breath',
    ],
    techniqueKeys: [],
    difficulty: 'beginner',
    icon: 'CircuitBoard',
  },
  {
    id: 'scapular-retractions',
    type: 'body',
    category: 'back',
    name: 'Scapular Retractions',
    nameKey: 'scapularRetractions',
    description: 'Pull your shoulder blades down and back while maintaining arm position.',
    descriptionKey: 'scapularRetractionsDesc',
    benefits: [
      'Strengthens scapular muscles',
      'Improves upper back posture',
      'Enhances symmetry',
      'Stabilizes shoulder blades',
    ],
    benefitsKeys: [
      'scapularRetractionsBenefits',
    ],
    duration: 4,
    repetitions: 15,
    sideControl: 'both',
    warnings: [
      'Focus on controlled movement',
      'Avoid using momentum',
      'Engage muscles consciously',
    ],
    warningsKeys: [
      'scapularRetractionsWarnings',
    ],
    technique: [
      'Start with arms at sides',
      'Pull shoulder blades down',
      'Pull shoulder blades together',
      'Hold contraction briefly',
      'Release with control',
      'Maintain arm position',
      'Focus on rhomboids engagement',
    ],
    techniqueKeys: [],
    difficulty: 'intermediate',
    icon: 'ArrowLeft',
  },
  {
    id: 'posture-alignment',
    type: 'body',
    category: 'posture',
    name: 'Posture Alignment',
    nameKey: 'postureAlignment',
    description: 'Practice standing with weight evenly distributed, shoulders back, head aligned.',
    descriptionKey: 'postureAlignmentDesc',
    benefits: [
      'Improves overall body symmetry',
      'Reduces strain',
      'Enhances appearance',
      'Promotes spinal health',
    ],
    benefitsKeys: [
      'postureAlignmentBenefits',
    ],
    duration: 60,
    sideControl: 'both',
    warnings: [
      'Check alignment in mirror',
      'Practice regularly',
      'Avoid hyper-extending',
    ],
    warningsKeys: [
      'postureAlignmentWarnings',
    ],
    technique: [
      'Stand with feet shoulder-width apart',
      'Distribute weight evenly',
      'Engage core muscles',
      'Pull shoulders back and down',
      'Keep head aligned with spine',
      'Chin parallel to floor',
      'Hold and breathe naturally',
    ],
    techniqueKeys: [],
    difficulty: 'beginner',
    icon: 'User',
  },
  {
    id: 'weight-distribution',
    type: 'body',
    category: 'posture',
    name: 'Weight Distribution Training',
    nameKey: 'weightDistribution',
    description: 'Practice shifting weight evenly between left and right feet while standing.',
    descriptionKey: 'weightDistributionDesc',
    benefits: [
      'Corrects weight imbalances',
      'Improves balance awareness',
      'Reduces asymmetry',
      'Enhances proprioception',
    ],
    benefitsKeys: [
      'weightDistributionBenefits',
    ],
    duration: 20,
    repetitions: 10,
    sideControl: 'both',
    warnings: [
      'Use a scale or level surface',
      'Practice with eyes closed for challenge',
      'Start slowly',
    ],
    warningsKeys: [
      'weightDistributionWarnings',
    ],
    technique: [
      'Stand with feet shoulder-width',
      'Shift weight to left side',
      'Hold briefly',
      'Shift to right side',
      'Hold briefly',
      'Find center balance',
      'Feel weight distribution',
    ],
    techniqueKeys: [],
    difficulty: 'beginner',
    icon: 'Scale',
  },
  {
    id: 'spinal-alignment',
    type: 'body',
    category: 'posture',
    name: 'Spinal Alignment Check',
    nameKey: 'spinalAlignment',
    description: 'Use a wall or mirror to ensure your spine is straight from multiple angles.',
    descriptionKey: 'spinalAlignmentDesc',
    benefits: [
      'Identifies postural deviations',
      'Trains proper alignment',
      'Improves overall symmetry',
      'Develops postural awareness',
    ],
    benefitsKeys: [
      'spinalAlignmentBenefits',
    ],
    duration: 30,
    sideControl: 'both',
    warnings: [
      'Seek professional help for major deviations',
      'Focus on gradual improvement',
      'Don\'t force alignment',
    ],
    warningsKeys: [
      'spinalAlignmentWarnings',
    ],
    technique: [
      'Stand with back to wall',
      'Check head, shoulders, hips contact',
      'Turn to side view',
      'Check spine alignment',
      'Adjust position as needed',
      'Memorize correct feeling',
      'Practice without wall',
    ],
    techniqueKeys: [],
    difficulty: 'beginner',
    icon: 'RulerVertical',
  },
  {
    id: 'side-stretching',
    type: 'body',
    category: 'imbalance',
    name: 'Side-to-Side Stretching',
    nameKey: 'sideStretching',
    description: 'Perform gentle side stretches, ensuring equal duration on left and right sides.',
    descriptionKey: 'sideStretchingDesc',
    benefits: [
      'Improves flexibility symmetry',
      'Releases muscle tension',
      'Balances range of motion',
      'Enhances lateral flexibility',
    ],
    benefitsKeys: [
      'sideStretchingBenefits',
    ],
    duration: 15,
    repetitions: 6,
    sideControl: 'both',
    warnings: [
      'Keep movements controlled',
      'Avoid bouncing',
      'Breathe steadily',
    ],
    warningsKeys: [
      'sideStretchingWarnings',
    ],
    technique: [
      'Stand with feet shoulder-width',
      'Reach overhead with one arm',
      'Lean to opposite side',
      'Hold gentle stretch',
      'Return to center',
      'Switch sides',
      'Equal duration on both sides',
    ],
    techniqueKeys: [],
    difficulty: 'beginner',
    icon: 'ArrowLeftRight',
  },
  {
    id: 'unilateral-strengthening',
    type: 'body',
    category: 'imbalance',
    name: 'Unilateral Strengthening',
    nameKey: 'unilateralStrengthening',
    description: 'Perform exercises on weaker side first, then match repetitions on stronger side.',
    descriptionKey: 'unilateralStrengtheningDesc',
    benefits: [
      'Corrects strength imbalances',
      'Builds symmetrical development',
      'Prevents compensations',
      'Equalizes muscle strength',
    ],
    benefitsKeys: [
      'unilateralStrengtheningBenefits',
    ],
    duration: 10,
    repetitions: 12,
    sideControl: 'both',
    warnings: [
      'Use lighter weights on weaker side',
      'Focus on proper form first',
      'Don\'t rush progress',
    ],
    warningsKeys: [
      'unilateralStrengtheningWarnings',
    ],
    technique: [
      'Identify weaker side',
      'Start with weaker side',
      'Perform exercise with control',
      'Note number of reps',
      'Match reps on stronger side',
      'Don\'t exceed weaker side capacity',
      'Gradually increase over time',
    ],
    techniqueKeys: [],
    difficulty: 'intermediate',
    icon: 'Dumbbell',
  },
  {
    id: 'balance-awareness',
    type: 'body',
    category: 'imbalance',
    name: 'Balance Awareness Training',
    nameKey: 'balanceAwareness',
    description: 'Practice standing on one foot at a time, noting differences between left and right stability.',
    descriptionKey: 'balanceAwarenessDesc',
    benefits: [
      'Identifies balance asymmetries',
      'Improves proprioception',
      'Enhances coordination',
      'Strengthens stabilizer muscles',
    ],
    benefitsKeys: [
      'balanceAwarenessBenefits',
    ],
    duration: 20,
    repetitions: 4,
    sideControl: 'both',
    warnings: [
      'Use support if needed',
      'Practice near a wall for safety',
      'Progress gradually',
    ],
    warningsKeys: [
      'balanceAwarenessWarnings',
    ],
    technique: [
      'Stand on one foot',
      'Lift other foot slightly',
      'Maintain balance',
      'Hold for 10-15 seconds',
      'Note stability differences',
      'Switch to other foot',
      'Compare balance between sides',
    ],
    techniqueKeys: [],
    difficulty: 'beginner',
    icon: 'Feet',
  },
];

export const allExercises: Exercise[] = [...facialExercises, ...bodyExercises];

export function getExerciseById(id: string): Exercise | undefined {
  return allExercises.find(exercise => exercise.id === id);
}

export function getExercisesByCategory(category: string): Exercise[] {
  return allExercises.filter(exercise => exercise.category === category);
}

export function getExercisesByType(type: ExerciseType): Exercise[] {
  return allExercises.filter(exercise => exercise.type === type);
}

export function getFacialCategories(): string[] {
  const categories = new Set(facialExercises.map(ex => ex.category));
  return Array.from(categories);
}

export function getBodyCategories(): string[] {
  const categories = new Set(bodyExercises.map(ex => ex.category));
  return Array.from(categories);
}
